FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    python3 \
    python3-pip \
    kpartx \
    qemu-utils \
    git \
    sudo \
    curl \
    squashfs-tools

RUN pip3 install --upgrade pip setuptools wheel && \
    pip3 install diskimage-builder

COPY CC-Ubuntu /opt/CC-Ubuntu
VOLUME /opt/CC-Ubuntu
WORKDIR /opt/CC-Ubuntu

CMD python3 create-image.py -n focal -v arm64